// contact.tsx
import React from 'react';
import './Contact.css';

const Contact: React.FC = () => {
    return (
        <div className="container">
            <section className="contact">
                <h2>Contact Me</h2>
                <p>Feel free to reach out to me via email at <a id="email" href="mailto:u.atoev@innopolis.university">u.atoev@innopolis.university</a> or connect with me on social media.</p>
                <div className="social-media">
                    <a id="gh-link" href="https://github.com/Urvatullo" target="_blank" rel="noopener noreferrer">
                        <img src="photos/GitHub.svg.png" alt="GitHub" />
                    </a>
                    <a id="tg-link" href="https://t.me/urvatullo_atoev" target="_blank" rel="noopener noreferrer">
                        <img src="photos/Telegram.webp" alt="Telegram" />
                    </a>
                    <a href="https://www.facebook.com/urvatullo.atoev.16?mibextid=kFxxJD" target="_blank" rel="noopener noreferrer">
                        <img src="photos/fb_icon_325x325.png" alt="Facebook" />
                    </a>
                    <a href="https://www.instagram.com/urvatullo_atoev/" target="_blank" rel="noopener noreferrer">
                        <img src="photos/Instagram_logo_2022.svg.webp" alt="Instagram" />
                    </a>
                </div>
            </section>
        </div>
    );
};

export default Contact;

// src/routes/contact.svelte
<script>
  import githubImg from '$lib/photos/GitHub.svg.png';
  import telegramImg from '$lib/photos/Telegram.webp';
  import facebookImg from '$lib/photos/fb_icon_325x325.png';
  import instagramImg from '$lib/photos/Instagram_logo_2022.svg.webp';
</script>

<style>
  .contact {
    text-align: center;
  }
  .social-media a {
    margin: 0 15px;
    display: inline-block;
  }
  .social-media img {
    width: 50px;
    border-radius: 50%;
  }
</style>

<div class="contact">
  <h2>Contact Me</h2>
  <p>Feel free to reach out to me via email at <a href="mailto:u.atoev@innopolis.university">u.atoev@innopolis.university</a> or connect with me on social media.</p>
  <div class="social-media">
    <a href="https://github.com/Urvatullo" target="_blank">
      <img src={githubImg} alt="GitHub">
    </a>
    <a href="https://t.me/urvatullo_atoev" target="_blank">
      <img src={telegramImg} alt="Telegram">
    </a>
    <a href="https://www.facebook.com/urvatullo.atoev.16?mibextid=kFxxJD" target="_blank">
      <img src={facebookImg} alt="Facebook">
    </a>
    <a href="https://www.instagram.com/urvatullo_atoev/" target="_blank">
      <img src={instagramImg} alt="Instagram">
    </a>
  </div>
</div>
